# Generated by Django 5.2.8 on 2025-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, max_length=1000)),
                ('store', models.CharField(choices=[('Flipkart', 'Flipkart'), ('myntra', 'Myntra'), ('meesho', 'Meesho')], max_length=20)),
                ('affiliate_link', models.URLField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
